---
- hosts: all
  become: false
  connection: local
  vars:
    terraform_version: 0.11.13
  tasks:

    - name: Add custom bashprofile
      copy:
        src: bash_profile.sh
        dest: "~/.bash_profile"

    - name: install homebrew
      shell: "/usr/bin/ruby -e \"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)\""
      args:
        creates: /usr/local/bin/brew

    - name: Install things from brew cask
      shell: "brew cask install {{ item }}"
      args:
        creates: "/Applications/{{ item }}"
      with_items:
        - alfred
        - vlc
        - iterm2
        - java
        - google-chrome
        - visual-studio-code
        - virtualbox
        - virtualbox-extension-pack
        - vagrant
        - firefox
        - google-backup-and-sync
        - github
        - sourcetree
        - charles
        - spotify
        - beyond-compare
        - dashlane
        - dash 
        - cyberduck
        - pgadmin4
        - obs
        - zoomus
        - slack

    - name: Install vagrant manager
      shell: "vagrant plugin install vagrant-hostmanager"

    - name: Install visual studio code extensions
      shell: "code --install-extension {{ item }}"
      with_items:
        - Shan.code-settings-sync

    - name: Add custom settings for VS Code
      copy:
        src: settings.json
        dest: "~/Library/Application Support/Code/User/settings.json"
        force: yes

    - name: Install things from brew
      shell: "brew install {{ item }}"
      args:
        creates: "/usr/local/Cellar/{{ item }}"
      with_items:
        - docker
        - python3
        - wget
        - postgresql
        - go 
        - node
        - git
        - awscli
        - bash-completion
        - htop
        - aws-shell
        - rbenv
        - ruby-build
        - graphviz
        - packer
        - cli53
        - git
        - mysql
        - sqlite

    - name: install git completion
      shell: "curl -o ~/.git-prompt.sh https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh"
      args:
        creates: ~/.git-prompt.sh
  
    - name: Install Terraform 
      shell: "wget https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_darwin_amd64.zip && unzip terraform_{{ terraform_version }}_darwin_amd64.zip -d /usr/local/bin/"
      args:
        chdir: /tmp
        creates: /usr/local/bin/terraform
    
    - name: source bash profile
      shell: ". ~/.bash_profile"

    - include: tasks/install-dmg.yml appName=Docker dmgURL=https://download.docker.com/mac/stable/Docker.dmg

    - include: tasks/install-dmg.yml appName=FortiClient dmgURL=https://filestore.fortinet.com/forticlient/downloads/FortiClientVPNOnlineInstaller_6.4.dmg

    - include: tasks/install-dmg.yml appName=WhatsApp dmgURL=https://web.whatsapp.com/desktop/mac/files/WhatsApp.dmg

    - include: tasks/rails.yml
